import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        <div className="container-max">
          <header className="glass-card p-4 mb-6 flex items-center justify-between">
            <div className="text-white font-semibold">AgentBuddy</div>
            <nav className="flex items-center gap-4">
              <a href="/" className="text-sm opacity-80 hover:opacity-100">Home</a>
              <a href="/dashboard" className="text-sm opacity-80 hover:opacity-100">Dashboard</a>
            </nav>
          </header>
        {children}
        </div>
      </body>
    </html>
  );
}
